### ISSUE TITLE
AttributeError (Python 3.7.3)

### ISSUE THREAD

**Issue by guidot** [viczem/ansible-keepass#2]
Both keepass.py and kpsock.py fail with an Attribute error `'bytes' object has no attribute 'encode'`.
Is it maybe because Python 3.7?

**Comment by viczem** [comment]
Please post a traceback of the error

**Comment by guidot** [comment]
I'm on a different machine that actually has pyton 3.6 installed. But it shows the same error:

`bash> python3 kpsock.py test.kdbx 
Password: 
## Open KeePass socket
## Close KeePass socket
Traceback (most recent call last):
  File "kpsock.py", line 114, in <module>
    run(_arg.kdbx, _psw, _arg.key, int(_arg.ttl))
  File "kpsock.py", line 32, in run
    with PyKeePass(kdbx, psw, kdbx_key) as kp:
  File "/usr/lib/python3.6/site-packages/pykeepass/pykeepass.py", line 41, in __init__
    transformed_key=transformed_key
  File "/usr/lib/python3.6/site-packages/pykeepass/pykeepass.py", line 61, in read
    transformed_key=transformed_key
  File "/usr/lib/python3.6/site-packages/construct/core.py", line 325, in parse_file
    return self.parse_stream(f, **contextkw)
  File "/usr/lib/python3.6/site-packages/construct/core.py", line 316, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "/usr/lib/python3.6/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/lib/python3.6/site-packages/construct/core.py", line 1979, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/usr/lib/python3.6/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/lib/python3.6/site-packages/construct/core.py", line 2468, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/usr/lib/python3.6/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/lib/python3.6/site-packages/construct/core.py", line 3663, in _parse
    return sc._parsereport(stream, context, path)
  File "/usr/lib/python3.6/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/lib/python3.6/site-packages/construct/core.py", line 1979, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/usr/lib/python3.6/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/lib/python3.6/site-packages/construct/core.py", line 2468, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/usr/lib/python3.6/site-packages/construct/core.py", line 328, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/lib/python3.6/site-packages/construct/core.py", line 2604, in _parse
    return self.func(context) if callable(self.func) else self.func
  File "/usr/lib/python3.6/site-packages/pykeepass/kdbx_parsing/kdbx4.py", line 56, in compute_transformed
    key_composite
  File "/usr/lib/python3.6/site-packages/pykeepass/kdbx_parsing/common.py", line 90, in aes_kdf
    keyfile=keyfile
  File "/usr/lib/python3.6/site-packages/pykeepass/kdbx_parsing/common.py", line 107, in compute_key_composite
    password_composite = hashlib.sha256(password.encode('utf-8')).digest()
AttributeError: 'bytes' object has no attribute 'encode'
`

**Comment by viczem** [comment]
I have no idea how to reproduce the problem.  According to the traceback the error raised in depended package `pykeepass`, because expected a password in string type.

I'm added validation in `kpsock.py` for entered password to [convert bytes to string](https://github.com/viczem/ansible-keepass/blob/998c1a48fcd1b29ee3e287fa68a1a632fbf2a639/kpsock.py#L152). 

Not sure that will fix the error. Please check if possible.
