### ISSUE TITLE
 KeePass: socket connection failed when used in parallel

### ISSUE THREAD

**Issue by maestrx** [viczem/ansible-keepass#34]
Hello,

This plugin has issues when used in parallel. When executed on group of targets, some systemtically fail, always in the same way.  Ive tried to debug and manage to improve somehow with samll patch. 

```
TASK [01-ilo-config-initial : Get Interface 1 config] **************************************************************************************************************************************************************
fatal: [US02-P-SVR-ESXI01-i -> localhost]: FAILED! => {"msg": "An unhandled exception occurred while templating '{{ lookup('viczem.keepass.keepass', 'servers-iLo/'+inventory_hostname, 'password') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while running the lookup plugin 'viczem.keepass.keepass'. Error was a <class 'ansible.errors.AnsibleError'>, original message: KeePass: socket connection failed for /test/keepass.kdbx. KeePass: socket connection failed for /test/keepass.kdbx"}
fatal: [US02-P-SVR-ESXI02-i -> localhost]: FAILED! => {"msg": "An unhandled exception occurred while templating '{{ lookup('viczem.keepass.keepass', 'servers-iLo/'+inventory_hostname, 'password') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while running the lookup plugin 'viczem.keepass.keepass'. Error was a <class 'ansible.errors.AnsibleError'>, original message: KeePass: socket connection failed for /test/keepass.kdbx. KeePass: socket connection failed for /test/keepass.kdbx"}
fatal: [US02-P-SVR-ESXI03-i -> localhost]: FAILED! => {"msg": "An unhandled exception occurred while templating '{{ lookup('viczem.keepass.keepass', 'servers-iLo/'+inventory_hostname, 'password') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while running the lookup plugin 'viczem.keepass.keepass'. Error was a <class 'ansible.errors.AnsibleError'>, original message: KeePass: socket connection failed for /test/keepass.kdbx. KeePass: socket connection failed for /test/keepass.kdbx"}
fatal: [US02-M-SVR-ESXI01-i -> localhost]: FAILED! => {"msg": "An unhandled exception occurred while templating '{{ lookup('viczem.keepass.keepass', 'servers-iLo/'+inventory_hostname, 'password') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while running the lookup plugin 'viczem.keepass.keepass'. Error was a <class 'ansible.errors.AnsibleError'>, original message: KeePass: socket connection failed for /test/keepass.kdbx. KeePass: socket connection failed for /test/keepass.kdbx"}
ok: [US02-P-SVR-ESXI09-i -> localhost]
ok: [US02-P-SVR-ESXI11-i -> localhost]
ok: [US02-M-SVR-ESXI02-i -> localhost]
ok: [US02-P-SVR-ESXI10-i -> localhost]

```

 Ive tried to debug and manage to improve somehow with small retry patch. 

```
TASK [01-ilo-config-initial : Get Interface 1 config] **************************************************************************************************************************************************************
Traceback (most recent call last):
  File "/root/.ansible/collections/ansible_collections/viczem/keepass/plugins/lookup/keepass.py", line 441, in <module>
    _keepass_socket(kdbx, key, kdbx_sock, args.ttl, password)
  File "/root/.ansible/collections/ansible_collections/viczem/keepass/plugins/lookup/keepass.py", line 260, in _keepass_socket
    conn.send(
BrokenPipeError: [Errno 32] Broken pipe
fatal: [US02-M-SVR-ESXI02-i -> localhost]: FAILED! => {"msg": "An unhandled exception occurred while templating '{{ lookup('viczem.keepass.keepass', 'servers-iLo/'+inventory_hostname, 'password') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while running the lookup plugin 'viczem.keepass.keepass'. Error was a <class 'ConnectionRefusedError'>, original message: [Errno 111] Connection refused. [Errno 111] Connection refused"}
fatal: [US02-M-SVR-ESXI01-i -> localhost]: FAILED! => {"msg": "An unhandled exception occurred while templating '{{ lookup('viczem.keepass.keepass', 'servers-iLo/'+inventory_hostname, 'password') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while running the lookup plugin 'viczem.keepass.keepass'. Error was a <class 'ConnectionRefusedError'>, original message: [Errno 111] Connection refused. [Errno 111] Connection refused"}
ok: [US02-P-SVR-ESXI02-i -> localhost]
ok: [US02-P-SVR-ESXI03-i -> localhost]
ok: [US02-P-SVR-ESXI11-i -> localhost]
ok: [US02-P-SVR-ESXI01-i -> localhost]
ok: [US02-P-SVR-ESXI09-i -> localhost]
ok: [US02-P-SVR-ESXI10-i -> localhost]
```

```
--- keepass_orig.py     2022-11-02 17:50:04.000000000 -0400
+++ keepass.py  2022-11-02 17:58:21.000000000 -0400
@@ -123,12 +123,15 @@
                             success = True
                         else:
                             raise AnsibleError("KeePass: wrong dbx password")
+                    else:
+                        raise
                     sock.close()
                     break
                 except FileNotFoundError:
                     # wait until the above command open the socket
                     time.sleep(1)
-
+                except:
+                    time.sleep(1)                    
             if not success:
                 raise AnsibleError("KeePass: socket connection failed for %s" % var_dbx)
 
@@ -243,7 +246,9 @@
 
                         # CMD: fetch
                         # Read data from decrypted KeePass file
-                        if cmd != "fetch":
+                        if cmd == "password":
+                            conn.send(_resp("password", 0))
+                        elif cmd != "fetch":
                             conn.send(_resp("fetch", 1, "unknown command '%s'" % cmd))
                             break
 
```

Any idea how to make this plugin parallel ready?

Thanks

**Comment by maestrx** [comment]
FYI: ansible-playbook main.yaml -f1 fixes the issue, ansible-playbook main.yaml -f2 is succeeding 90% of teh time...

**Comment by viczem** [comment]
If you open the keepass socket manually, it will work correctly in parallel, e.g. `python ~/.ansible/collections/ansible_collections/viczem/keepass/plugins/lookup/keepass.py --ask-pass`
(`ansible-galaxy collection list` to show directory where the collection was installed)

Now the socket opening [here](https://github.com/viczem/ansible-keepass/blob/main/plugins/lookup/keepass.py#L91) at first call of the lookup plugin. This is to avoid manually starting the socket before use Ansible. When use in parallel, this becomes a problem. It has already been proposed to solve it by opening a separate socket for each process. But I don't think this is the best idea.
