### ISSUE TITLE
Unable to get attachments

### ISSUE THREAD

**Issue by marcpaulchand** [viczem/ansible-keepass#45]
Hello

First of all thanks for your great lookup !

I'm moving close to you regarding an issue i encounter.

I tried to get a file content from your lookup but the only answer i had was the following : 
```shell
TASK [debug] *******************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'viczem.keepass.keepass'. Error was a <class 'ansible.errors.AnsibleError'>, original message: KeePass: 'attachment 'vlt-02.lan' is not
found for '['Infra', 'PKI', 'Certificates', 'vlt-02.lan']'' has error 'fetch'. KeePass: 'attachment 'vlt-02.lan' is not found for '['Infra', 'PKI', 'Certificates', 'vlt-02.lan']'' has error 'fetch'"}

PLAY RECAP ********************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```
But i check directly, the file is present.
```shell
$ keepassxc-cli show ~/Keepass/Passwords.kdbx /Infra/PKI/Certificates/vlt-02.lan --show-attachments                                                       
Password for /home/paul/Sync/Keypass/Passwords.kdbx :
Title: vlt-02.lan
UserName:
Password: PROTECTED
URL:
Notes:
Uuid: {149d5b66-yyyy-xxxx-zzzz-cc95ee4dc88a}
Tags:

Attachments:
  cert.pem (1,3 KiB)
  vlt-02.key (3,2 KiB)
  vlt-02.pem (1,3 KiB)
```

How can i help you ?

I tried to add a `print()` instruction in your lookup and nothing happen. I also tried a raise Exception and it wasn't relevant

I only have this by adding mmore verbosity
```shell
exception during Jinja2 execution: Traceback (most recent call last):
  File "/home/paul/.ansible/collections/ansible_collections/viczem/keepass/plugins/lookup/keepass.py", line 180, in _send
    raise AnsibleError("KeePass: '%s' has error '%s'" % (resp[2], cmd))
ansible.errors.AnsibleError: KeePass: 'attachment 'vlt-02.lan' is not found for '['Infra', 'PKI', 'Certificates', 'vlt-02.lan']'' has error 'fetch'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ansible/template/__init__.py", line 831, in _lookup
    ran = instance.run(loop_terms, variables=self._available_variables, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paul/.ansible/collections/ansible_collections/viczem/keepass/plugins/lookup/keepass.py", line 152, in run
    return self._send(socket_path, "fetch", terms)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paul/.ansible/collections/ansible_collections/viczem/keepass/plugins/lookup/keepass.py", line 183, in _send
    raise AnsibleError(str(e))
ansible.errors.AnsibleError: KeePass: 'attachment 'vlt-02.lan' is not found for '['Infra', 'PKI', 'Certificates', 'vlt-02.lan']'' has error 'fetch'
```

**Comment by viczem** [comment]
Hello

In your case it would be correct

- `{{ lookup('viczem.keepass.keepass', 'Infra/PKI/Certificates/vlt-02.lan', 'attachments', 'cert.pem')}}`
- `{{ lookup('viczem.keepass.keepass', 'Infra/PKI/Certificates/vlt-02.lan', 'attachments', 'vlt-02.key')}}`
- `{{ lookup('viczem.keepass.keepass', 'Infra/PKI/Certificates/vlt-02.lan', 'attachments', 'vlt-02.pem')}}`

Please check it
